stages:
  - Test

Tests:
  stage: Test
  tags:
    - docker
  image: python:latest
  before_script:
    - pip install -r requirements.txt
    - pip install coveralls
  script:
    - coverage run --include=wallhavenapi.py tests.py
    - coveralls
    - bash <(curl -s https://codecov.io/bash)
  only: 
    - master